/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppDashboardRouteRouteImport } from './routes/_app/dashboard/route'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppDashboardInvoicesRouteRouteImport } from './routes/_app/dashboard/invoices/route'
import { Route as AppDashboardInvoicesIndexRouteImport } from './routes/_app/dashboard/invoices/index'
import { Route as AppDashboardCustomersIndexRouteImport } from './routes/_app/dashboard/customers/index'
import { Route as AppDashboardInvoicesInvoiceIdRouteImport } from './routes/_app/dashboard/invoices/$invoiceId'
import { Route as AppDashboardCustomersAddRouteImport } from './routes/_app/dashboard/customers/add'
import { Route as AppDashboardCustomersCustomerIdRouteImport } from './routes/_app/dashboard/customers/$customerId'
import { Route as AppDashboardCustomersEditCustomerIdRouteImport } from './routes/_app/dashboard/customers/edit.$customerId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const AppDashboardInvoicesRouteRoute =
  AppDashboardInvoicesRouteRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AppDashboardRouteRoute,
  } as any)
const AppDashboardInvoicesIndexRoute =
  AppDashboardInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDashboardInvoicesRouteRoute,
  } as any)
const AppDashboardCustomersIndexRoute =
  AppDashboardCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AppDashboardRouteRoute,
  } as any)
const AppDashboardInvoicesInvoiceIdRoute =
  AppDashboardInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AppDashboardInvoicesRouteRoute,
  } as any)
const AppDashboardCustomersAddRoute =
  AppDashboardCustomersAddRouteImport.update({
    id: '/customers/add',
    path: '/customers/add',
    getParentRoute: () => AppDashboardRouteRoute,
  } as any)
const AppDashboardCustomersCustomerIdRoute =
  AppDashboardCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AppDashboardRouteRoute,
  } as any)
const AppDashboardCustomersEditCustomerIdRoute =
  AppDashboardCustomersEditCustomerIdRouteImport.update({
    id: '/customers/edit/$customerId',
    path: '/customers/edit/$customerId',
    getParentRoute: () => AppDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/dashboard/invoices': typeof AppDashboardInvoicesRouteRouteWithChildren
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dashboard/customers/$customerId': typeof AppDashboardCustomersCustomerIdRoute
  '/dashboard/customers/add': typeof AppDashboardCustomersAddRoute
  '/dashboard/invoices/$invoiceId': typeof AppDashboardInvoicesInvoiceIdRoute
  '/dashboard/customers/': typeof AppDashboardCustomersIndexRoute
  '/dashboard/invoices/': typeof AppDashboardInvoicesIndexRoute
  '/dashboard/customers/edit/$customerId': typeof AppDashboardCustomersEditCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dashboard/customers/$customerId': typeof AppDashboardCustomersCustomerIdRoute
  '/dashboard/customers/add': typeof AppDashboardCustomersAddRoute
  '/dashboard/invoices/$invoiceId': typeof AppDashboardInvoicesInvoiceIdRoute
  '/dashboard/customers': typeof AppDashboardCustomersIndexRoute
  '/dashboard/invoices': typeof AppDashboardInvoicesIndexRoute
  '/dashboard/customers/edit/$customerId': typeof AppDashboardCustomersEditCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/dashboard/invoices': typeof AppDashboardInvoicesRouteRouteWithChildren
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dashboard/customers/$customerId': typeof AppDashboardCustomersCustomerIdRoute
  '/_app/dashboard/customers/add': typeof AppDashboardCustomersAddRoute
  '/_app/dashboard/invoices/$invoiceId': typeof AppDashboardInvoicesInvoiceIdRoute
  '/_app/dashboard/customers/': typeof AppDashboardCustomersIndexRoute
  '/_app/dashboard/invoices/': typeof AppDashboardInvoicesIndexRoute
  '/_app/dashboard/customers/edit/$customerId': typeof AppDashboardCustomersEditCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/dashboard/invoices'
    | '/dashboard/'
    | '/dashboard/customers/$customerId'
    | '/dashboard/customers/add'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/customers/'
    | '/dashboard/invoices/'
    | '/dashboard/customers/edit/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/dashboard/customers/$customerId'
    | '/dashboard/customers/add'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/customers'
    | '/dashboard/invoices'
    | '/dashboard/customers/edit/$customerId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_app/dashboard/invoices'
    | '/_app/dashboard/'
    | '/_app/dashboard/customers/$customerId'
    | '/_app/dashboard/customers/add'
    | '/_app/dashboard/invoices/$invoiceId'
    | '/_app/dashboard/customers/'
    | '/_app/dashboard/invoices/'
    | '/_app/dashboard/customers/edit/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/dashboard/invoices': {
      id: '/_app/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof AppDashboardInvoicesRouteRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/dashboard/invoices/': {
      id: '/_app/dashboard/invoices/'
      path: '/'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof AppDashboardInvoicesIndexRouteImport
      parentRoute: typeof AppDashboardInvoicesRouteRoute
    }
    '/_app/dashboard/customers/': {
      id: '/_app/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof AppDashboardCustomersIndexRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/dashboard/invoices/$invoiceId': {
      id: '/_app/dashboard/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof AppDashboardInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppDashboardInvoicesRouteRoute
    }
    '/_app/dashboard/customers/add': {
      id: '/_app/dashboard/customers/add'
      path: '/customers/add'
      fullPath: '/dashboard/customers/add'
      preLoaderRoute: typeof AppDashboardCustomersAddRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/dashboard/customers/$customerId': {
      id: '/_app/dashboard/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/dashboard/customers/$customerId'
      preLoaderRoute: typeof AppDashboardCustomersCustomerIdRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/dashboard/customers/edit/$customerId': {
      id: '/_app/dashboard/customers/edit/$customerId'
      path: '/customers/edit/$customerId'
      fullPath: '/dashboard/customers/edit/$customerId'
      preLoaderRoute: typeof AppDashboardCustomersEditCustomerIdRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
  }
}

interface AppDashboardInvoicesRouteRouteChildren {
  AppDashboardInvoicesInvoiceIdRoute: typeof AppDashboardInvoicesInvoiceIdRoute
  AppDashboardInvoicesIndexRoute: typeof AppDashboardInvoicesIndexRoute
}

const AppDashboardInvoicesRouteRouteChildren: AppDashboardInvoicesRouteRouteChildren =
  {
    AppDashboardInvoicesInvoiceIdRoute: AppDashboardInvoicesInvoiceIdRoute,
    AppDashboardInvoicesIndexRoute: AppDashboardInvoicesIndexRoute,
  }

const AppDashboardInvoicesRouteRouteWithChildren =
  AppDashboardInvoicesRouteRoute._addFileChildren(
    AppDashboardInvoicesRouteRouteChildren,
  )

interface AppDashboardRouteRouteChildren {
  AppDashboardInvoicesRouteRoute: typeof AppDashboardInvoicesRouteRouteWithChildren
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardCustomersCustomerIdRoute: typeof AppDashboardCustomersCustomerIdRoute
  AppDashboardCustomersAddRoute: typeof AppDashboardCustomersAddRoute
  AppDashboardCustomersIndexRoute: typeof AppDashboardCustomersIndexRoute
  AppDashboardCustomersEditCustomerIdRoute: typeof AppDashboardCustomersEditCustomerIdRoute
}

const AppDashboardRouteRouteChildren: AppDashboardRouteRouteChildren = {
  AppDashboardInvoicesRouteRoute: AppDashboardInvoicesRouteRouteWithChildren,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardCustomersCustomerIdRoute: AppDashboardCustomersCustomerIdRoute,
  AppDashboardCustomersAddRoute: AppDashboardCustomersAddRoute,
  AppDashboardCustomersIndexRoute: AppDashboardCustomersIndexRoute,
  AppDashboardCustomersEditCustomerIdRoute:
    AppDashboardCustomersEditCustomerIdRoute,
}

const AppDashboardRouteRouteWithChildren =
  AppDashboardRouteRoute._addFileChildren(AppDashboardRouteRouteChildren)

interface AppRouteChildren {
  AppDashboardRouteRoute: typeof AppDashboardRouteRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRouteRoute: AppDashboardRouteRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
